version: "2"
services:
  appLexBuildDb:
      image: "microsoft/mssql-server-linux"
      environment:
          SA_PASSWORD: "AppLexDevBuild2018!"
          ACCEPT_EULA: ""
          ports:
              -"1433:1433"
      ports:
        - "2433:1433"
  build:
    image: "strangefruit.ddns.net:443/appLex/services/build:latest"
    ports:
      - "9010:80"
    depends_on:
      - appLexBuildDb
  # authentication:
  #   image: "authentication"
  #   build: "./Services/authentication/thss-authentication-microservice"
  #   ports:
  #     - "8089:80"
  #   depends_on: 
  #     - db
  # prometheus:
  #   image: "prom/prometheus"
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
  #   command: --config.file=/etc/prometheus/prometheus.yml
  # grafana:
  #   image: "grafana/grafana"
  #   ports:
  #     - "3000:3000"