version: "3"
services:
  lexioBuildDb:
    image: "microsoft/mssql-server-linux"
    environment:
        SA_PASSWORD: "lexioDevBuild2018!"
        ACCEPT_EULA: "Y"
        ports:
            -"1433:1433"
    ports:
      - "1433:1433"
  build:
    image: "build"
    build: "./thss-lexio-build/thss-lexio-build"
    ports:
      - "4243:80"
    depends_on:
      - lexioBuildDb
#  web:
#    container_name: web
#    build:
#      context: ./thss-lexio-build-frontend
#      dockerfile: Dockerfile
#    volumes:
#      - '.:/usr/src/app'
#      - '/usr/src/app/node_modules'
#    ports:
#      - '9011:3000'
#    environment:
#      - NODE_ENV=development
  # authentication:
  #   image: "authentication"
  #   build: "./Services/authentication/thss-authentication-microservice"
  #   ports:
  #     - "8089:80"
  #   depends_on: 
  #     - db
  # prometheus:
  #   image: "prom/prometheus"
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
  #   command: --config.file=/etc/prometheus/prometheus.yml
  # grafana:
  #   image: "grafana/grafana"
  #   ports:
  #     - "3000:3000"
